name: plan_tasks
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4 # Utilizar o SQLite
  path_provider: ^2.0.2 # Encontrar locais comumente usados no sistema de arquivos
  shared_preferences: ^2.0.7 # Preferências compartilhadas
  flutter_launcher_icons: ^0.9.2 # Criar ícone app
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: 'assets/imgs/icone.png'
  adaptive_icon_background: '#006400'
  adaptive_icon_foreground: 'assets/imgs/icone.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/imgs/image1.png
    - assets/imgs/image2.png
    - assets/imgs/splash.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900


